config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get 'home/about'
  devise_for :agents
  resources :invitations
  resources :smartlocks
  resources :properties
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Smart Home', root_path, class:"navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <% if agent_signed_in? %>

        <li class="nav-item">
        <%= link_to 'Edit Profile', edit_agent_registration_path, class:"nav-link active"%>
        </li>
      
        


        <li class="nav-item dropdown">
          <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Property
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Add Properties', new_property_path, class:"dropdown-item "%>
          <%=  link_to 'Properties', properties_path,class:"dropdown-item "%>  
          </ul>
        </li>


          <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
          <%= link_to 'Log out', destroy_agent_session_path, 'data-method' => :delete, class:'nav-link' %>
          </li>
          

        <%else%>
          <li class="nav-item">
          <%= link_to 'Sign Up', new_agent_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
          <%= link_to 'Log in', new_agent_session_path, class:"nav-link"%>
          </li>
        
          
      <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>