config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get 'home/about'
  devise_for :agents
  resources :invitations
  resources :smartlocks
  resources :properties
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :agent
  belongs_to :lockcode
  belongs_to :property
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: %i[ show edit update destroy ]

  # GET /invitations or /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1 or /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations or /invitations.json
  def create
    @invitation = Invitation.new(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to invitation_url(@invitation), notice: "Invitation was successfully created." }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1 or /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to invitation_url(@invitation), notice: "Invitation was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url, notice: "Invitation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invitation_params
      params.require(:invitation).permit(:recipient_email, :agent_id, :lockcode_id, :property_id)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_with(model: invitation, local: true) do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recipient_email %>
    <%= form.text_field :recipient_email %>
  </div>

  <div class="field">
    <%= form.label :agent_id %>
    <%= form.text_field :agent_id %>
  </div>

  <div class="field">
    <%= form.label :lockcode_id %>
    <%= form.text_field :lockcode_id %>
  </div>

  <div class="field">
    <%= form.label :property_id %>
    <%= form.text_field :property_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Recipient email</th>
      <th>Agent</th>
      <th>Lockcode</th>
      <th>Property</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.recipient_email %></td>
        <td><%= invitation.agent_id %></td>
        <td><%= invitation.lockcode_id %></td>
        <td><%= invitation.property_id %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<p>
  <strong>Recipient email:</strong>
  <%= @invitation.recipient_email %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @invitation.agent_id %>
</p>

<p>
  <strong>Lockcode:</strong>
  <%= @invitation.lockcode_id %>
</p>

<p>
  <strong>Property:</strong>
  <%= @invitation.property_id %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>